name: edulure_mobile
version: 0.1.0+1
description: Flutter companion app for the Edulure learning platform.
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <7.0.0"
flutter:
  uses-material-design: true
