name: edulure_mobile
version: 0.1.0+1
description: Flutter companion app for the Edulure learning platform.
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  url_launcher: ^6.2.5
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1
  epub_view: ^3.2.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.0.0
  sentry_flutter: ^8.7.0
  pretty_dio_logger: ^1.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
