version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend-nodejs"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
    reviewers:
      - "edulure-devops"
  - package-ecosystem: "npm"
    directory: "/frontend-reactjs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "pub"
    directory: "/Edulure-Flutter"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
