version: "3.9"
services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: edulure
      POSTGRES_PASSWORD: edulure
      POSTGRES_DB: edulure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "edulure"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://edulure:edulure@postgres:5432/edulure
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.frontend
    depends_on:
      backend:
        condition: service_started
    environment:
      VITE_API_BASE_URL: http://backend:8080/api/v1
    ports:
      - "3000:80"

volumes:
  postgres_data:
