-- Legacy placeholder retained for historical reference.
-- Database provisioning is now handled via scripts/install-db.js, which
-- creates the target schema using environment-specific credentials and
-- runs Knex migrations. This file intentionally contains no executable SQL.
