CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('user', 'instructor', 'admin') NOT NULL DEFAULT 'user',
  age INT UNSIGNED NULL,
  address VARCHAR(255) NULL,
  two_factor_enabled TINYINT(1) NOT NULL DEFAULT 0,
  two_factor_secret VARBINARY(255) NULL,
  two_factor_enrolled_at TIMESTAMP NULL DEFAULT NULL,
  two_factor_last_verified_at TIMESTAMP NULL DEFAULT NULL,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  failed_login_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  last_failed_login_at TIMESTAMP NULL DEFAULT NULL,
  locked_until TIMESTAMP NULL DEFAULT NULL,
  last_login_at TIMESTAMP NULL DEFAULT NULL,
  password_changed_at TIMESTAMP NULL DEFAULT NULL,
  last_verification_sent_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY users_email_unique (email),
  INDEX idx_users_role (role)
) ENGINE=InnoDB;
