apiVersion: 1
datasources:
  - name: Edulure Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    jsonData:
      timeInterval: 15s
      httpMethod: GET
    version: 1
    editable: false
