-- AUTO-GENERATED FILE. Update docs/design-system/design_tokens.json or research_insights.json and rerun sync-design-tokens.
DELETE FROM design_system_tokens;
INSERT INTO design_system_tokens (token_key, token_value, source, context, selector, token_category, display_order, metadata)
VALUES
  ('--screen-xs', '360px', 'base', NULL, ':root', 'screen', 1, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--screen-sm', '480px', 'base', NULL, ':root', 'screen', 2, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--screen-md', '768px', 'base', NULL, ':root', 'screen', 3, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--screen-lg', '1024px', 'base', NULL, ':root', 'screen', 4, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--screen-xl', '1280px', 'base', NULL, ':root', 'screen', 5, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--screen-2xl', '1536px', 'base', NULL, ':root', 'screen', 6, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-1', '0.25rem', 'base', NULL, ':root', 'space', 7, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-2', '0.5rem', 'base', NULL, ':root', 'space', 8, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-3', '0.75rem', 'base', NULL, ':root', 'space', 9, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-4', '1rem', 'base', NULL, ':root', 'space', 10, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-5', '1.25rem', 'base', NULL, ':root', 'space', 11, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-6', '1.5rem', 'base', NULL, ':root', 'space', 12, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-8', '2rem', 'base', NULL, ':root', 'space', 13, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-10', '2.5rem', 'base', NULL, ':root', 'space', 14, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-12', '3rem', 'base', NULL, ':root', 'space', 15, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--space-16', '4rem', 'base', NULL, ':root', 'space', 16, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--font-family-sans', '''Inter'', ui-sans-serif, system-ui', 'base', NULL, ':root', 'font', 17, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--font-size-root', '16px', 'base', NULL, ':root', 'font', 18, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--line-height-base', '1.5', 'base', NULL, ':root', 'general', 19, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-surface', '#ffffff', 'base', NULL, ':root', 'color', 20, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-surface-muted', '#f8fafc', 'base', NULL, ':root', 'color', 21, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-surface-subtle', '#f1f5f9', 'base', NULL, ':root', 'color', 22, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-border', 'rgba(15, 23, 42, 0.12)', 'base', NULL, ':root', 'color', 23, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-text', '#0f172a', 'base', NULL, ':root', 'color', 24, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-text-muted', '#475569', 'base', NULL, ':root', 'color', 25, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-text-subtle', '#64748b', 'base', NULL, ':root', 'color', 26, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-primary', '#2d62ff', 'base', NULL, ':root', 'color', 27, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-primary-dark', '#1f3bb3', 'base', NULL, ':root', 'color', 28, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-primary-soft', '#dbe4ff', 'base', NULL, ':root', 'color', 29, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-emerald', '#10b981', 'base', NULL, ':root', 'color', 30, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-amber', '#f59e0b', 'base', NULL, ':root', 'color', 31, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-rose', '#f43f5e', 'base', NULL, ':root', 'color', 32, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--radius-lg', '1.25rem', 'base', NULL, ':root', 'radius', 33, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--radius-xl', '2rem', 'base', NULL, ':root', 'radius', 34, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--radius-xxl', '2.75rem', 'base', NULL, ':root', 'radius', 35, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--radius-pill', '999px', 'base', NULL, ':root', 'radius', 36, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--uploads-progress-radius', '0.75rem', 'base', NULL, ':root', 'general', 37, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--shadow-card', '0 24px 60px -30px rgba(15, 23, 42, 0.18)', 'base', NULL, ':root', 'shadow', 38, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--shadow-card-strong', '0 32px 84px -36px rgba(15, 23, 42, 0.32)', 'base', NULL, ':root', 'shadow', 39, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--shadow-media', '0 40px 120px -48px rgba(15, 23, 42, 0.42)', 'base', NULL, ':root', 'shadow', 40, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--shadow-cta', '0 22px 52px -26px rgba(79, 70, 229, 0.7)', 'base', NULL, ':root', 'shadow', 41, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--gradient-hero', 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 52%, #111827 100%)', 'base', NULL, ':root', 'gradient', 42, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--gradient-marketing', 'linear-gradient(160deg, rgba(15, 23, 42, 0.98) 0%, rgba(30, 64, 175, 0.92) 65%, rgba(15, 23, 42, 0.96) 100%)', 'base', NULL, ':root', 'gradient', 43, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--gradient-cta', 'linear-gradient(135deg, #4338ca 0%, #6366f1 55%, #7c3aed 100%)', 'base', NULL, ':root', 'gradient', 44, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--gradient-cta-hover', 'linear-gradient(135deg, #3730a3 0%, #4f46e5 55%, #6d28d9 100%)', 'base', NULL, ':root', 'gradient', 45, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--motion-duration-fast', '120ms', 'base', NULL, ':root', 'motion', 46, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--motion-duration-medium', '220ms', 'base', NULL, ':root', 'motion', 47, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--motion-easing-standard', 'cubic-bezier(0.16, 1, 0.3, 1)', 'base', NULL, ':root', 'motion', 48, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--media-thumb-aspect', '16 / 10', 'base', NULL, ':root', 'media', 49, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--media-thumb-radius', '2.75rem', 'base', NULL, ':root', 'media', 50, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--skeleton-base', '#e2e8f0', 'base', NULL, ':root', 'skeleton', 51, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--skeleton-highlight', '#f8fafc', 'base', NULL, ':root', 'skeleton', 52, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-surface', '#ffffff', 'base', NULL, ':root', 'form', 53, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-surface-focus', '#f8fbff', 'base', NULL, ':root', 'form', 54, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-border', 'rgba(148, 163, 184, 0.45)', 'base', NULL, ':root', 'form', 55, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-border-strong', 'rgba(79, 70, 229, 0.45)', 'base', NULL, ':root', 'form', 56, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-shadow', '0 18px 45px -28px rgba(15, 23, 42, 0.35)', 'base', NULL, ':root', 'form', 57, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-padding-x', '1.25rem', 'base', NULL, ':root', 'form', 58, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-field-padding-y', '0.875rem', 'base', NULL, ':root', 'form', 59, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--form-label-letterspacing', '0.025em', 'base', NULL, ':root', 'form', 60, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--shadow-focus-ring', '0 0 0 3px rgba(45, 98, 255, 0.35)', 'base', NULL, ':root', 'shadow', 61, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--overlay-backdrop', 'rgba(15, 23, 42, 0.6)', 'base', NULL, ':root', 'overlay', 62, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--grid-min-column', '18rem', 'base', NULL, ':root', 'grid', 63, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--grid-gap', 'var(--space-6)', 'base', NULL, ':root', 'grid', 64, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('color-scheme', 'only light', 'base', NULL, ':root', 'color', 65, CAST('{"version":"2025-05-26","source":"base","context":null,"selector":":root"}' AS JSON)),
  ('--color-surface', '#0f172a', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 66, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-surface-muted', '#111c33', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 67, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-surface-subtle', '#17284a', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 68, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-border', 'rgba(226, 232, 240, 0.2)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 69, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-text', '#e2e8f0', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 70, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-text-muted', '#cbd5f5', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 71, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-text-subtle', '#a5b4fc', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 72, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-primary-soft', 'rgba(45, 98, 255, 0.24)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'color', 73, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--overlay-backdrop', 'rgba(15, 23, 42, 0.75)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'overlay', 74, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--shadow-card', '0 24px 60px -30px rgba(15, 23, 42, 0.4)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'shadow', 75, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--shadow-card-strong', '0 32px 84px -36px rgba(15, 23, 42, 0.6)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'shadow', 76, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--shadow-media', '0 40px 120px -48px rgba(15, 23, 42, 0.6)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'shadow', 77, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--shadow-cta', '0 22px 52px -26px rgba(99, 102, 241, 0.75)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'shadow', 78, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--gradient-hero', 'linear-gradient(135deg, #0b1120 0%, #1e1b4b 60%, #111827 100%)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'gradient', 79, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--gradient-marketing', 'linear-gradient(160deg, rgba(15, 23, 42, 1) 0%, rgba(30, 64, 175, 0.92) 55%, rgba(15, 23, 42, 0.96) 100%)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'gradient', 80, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--gradient-cta', 'linear-gradient(135deg, #4338ca 0%, #4f46e5 55%, #7c3aed 100%)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'gradient', 81, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--gradient-cta-hover', 'linear-gradient(135deg, #3730a3 0%, #4338ca 55%, #6d28d9 100%)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'gradient', 82, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--form-field-surface', 'rgba(15, 23, 42, 0.8)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'form', 83, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--form-field-surface-focus', 'rgba(30, 58, 138, 0.9)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'form', 84, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--form-field-border', 'rgba(148, 163, 184, 0.35)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'form', 85, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--form-field-border-strong', 'rgba(129, 140, 248, 0.55)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'form', 86, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--form-field-shadow', '0 22px 60px -34px rgba(15, 23, 42, 0.8)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'form', 87, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--skeleton-base', 'rgba(148, 163, 184, 0.35)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'skeleton', 88, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--skeleton-highlight', 'rgba(226, 232, 240, 0.35)', 'media', '@media (prefers-color-scheme: dark)', ':root', 'skeleton', 89, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-color-scheme: dark)","selector":":root"}' AS JSON)),
  ('--color-surface', '#ffffff', 'media', '@media (prefers-contrast: more)', ':root', 'color', 90, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-surface-muted', '#ffffff', 'media', '@media (prefers-contrast: more)', ':root', 'color', 91, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-surface-subtle', '#f8fafc', 'media', '@media (prefers-contrast: more)', ':root', 'color', 92, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-border', 'rgba(15, 23, 42, 0.4)', 'media', '@media (prefers-contrast: more)', ':root', 'color', 93, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-text', '#0b1120', 'media', '@media (prefers-contrast: more)', ':root', 'color', 94, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-text-muted', '#111c33', 'media', '@media (prefers-contrast: more)', ':root', 'color', 95, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-text-subtle', '#1e293b', 'media', '@media (prefers-contrast: more)', ':root', 'color', 96, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-primary', '#1d4ed8', 'media', '@media (prefers-contrast: more)', ':root', 'color', 97, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-primary-dark', '#1e3a8a', 'media', '@media (prefers-contrast: more)', ':root', 'color', 98, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-primary-soft', '#c7d2fe', 'media', '@media (prefers-contrast: more)', ':root', 'color', 99, CAST('{"version":"2025-05-26","source":"media","context":"@media (prefers-contrast: more)","selector":":root"}' AS JSON)),
  ('--color-surface', '#0f172a', 'data', NULL, '[data-theme=''dark'']', 'color', 100, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-surface-muted', '#111c33', 'data', NULL, '[data-theme=''dark'']', 'color', 101, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-surface-subtle', '#17284a', 'data', NULL, '[data-theme=''dark'']', 'color', 102, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-border', 'rgba(226, 232, 240, 0.2)', 'data', NULL, '[data-theme=''dark'']', 'color', 103, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-text', '#e2e8f0', 'data', NULL, '[data-theme=''dark'']', 'color', 104, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-text-muted', '#cbd5f5', 'data', NULL, '[data-theme=''dark'']', 'color', 105, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-text-subtle', '#a5b4fc', 'data', NULL, '[data-theme=''dark'']', 'color', 106, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-primary-soft', 'rgba(45, 98, 255, 0.24)', 'data', NULL, '[data-theme=''dark'']', 'color', 107, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--overlay-backdrop', 'rgba(15, 23, 42, 0.75)', 'data', NULL, '[data-theme=''dark'']', 'overlay', 108, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-theme=''dark'']"}' AS JSON)),
  ('--color-surface', '#ffffff', 'data', NULL, '[data-contrast=''high'']', 'color', 109, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-surface-muted', '#ffffff', 'data', NULL, '[data-contrast=''high'']', 'color', 110, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-surface-subtle', '#f8fafc', 'data', NULL, '[data-contrast=''high'']', 'color', 111, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-border', 'rgba(15, 23, 42, 0.4)', 'data', NULL, '[data-contrast=''high'']', 'color', 112, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-text', '#0b1120', 'data', NULL, '[data-contrast=''high'']', 'color', 113, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-text-muted', '#111c33', 'data', NULL, '[data-contrast=''high'']', 'color', 114, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-text-subtle', '#1e293b', 'data', NULL, '[data-contrast=''high'']', 'color', 115, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-primary', '#1d4ed8', 'data', NULL, '[data-contrast=''high'']', 'color', 116, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-primary-dark', '#1e3a8a', 'data', NULL, '[data-contrast=''high'']', 'color', 117, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--color-primary-soft', '#c7d2fe', 'data', NULL, '[data-contrast=''high'']', 'color', 118, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--shadow-card', '0 24px 60px -32px rgba(15, 23, 42, 0.4)', 'data', NULL, '[data-contrast=''high'']', 'shadow', 119, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--shadow-card-strong', '0 32px 84px -36px rgba(15, 23, 42, 0.6)', 'data', NULL, '[data-contrast=''high'']', 'shadow', 120, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--shadow-media', '0 40px 120px -46px rgba(15, 23, 42, 0.55)', 'data', NULL, '[data-contrast=''high'']', 'shadow', 121, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--shadow-cta', '0 22px 52px -24px rgba(30, 64, 175, 0.78)', 'data', NULL, '[data-contrast=''high'']', 'shadow', 122, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--gradient-hero', 'linear-gradient(135deg, #0f172a 0%, #1e3a8a 55%, #1e293b 100%)', 'data', NULL, '[data-contrast=''high'']', 'gradient', 123, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--gradient-marketing', 'linear-gradient(160deg, rgba(226, 232, 240, 1) 0%, rgba(191, 219, 254, 0.85) 45%, rgba(226, 232, 240, 1) 100%)', 'data', NULL, '[data-contrast=''high'']', 'gradient', 124, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--gradient-cta', 'linear-gradient(135deg, #1d4ed8 0%, #2563eb 55%, #4f46e5 100%)', 'data', NULL, '[data-contrast=''high'']', 'gradient', 125, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--gradient-cta-hover', 'linear-gradient(135deg, #1e3a8a 0%, #1d4ed8 55%, #4338ca 100%)', 'data', NULL, '[data-contrast=''high'']', 'gradient', 126, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--form-field-border', 'rgba(30, 64, 175, 0.55)', 'data', NULL, '[data-contrast=''high'']', 'form', 127, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON)),
  ('--form-field-border-strong', 'rgba(17, 94, 89, 0.55)', 'data', NULL, '[data-contrast=''high'']', 'form', 128, CAST('{"version":"2025-05-26","source":"data","context":null,"selector":"[data-contrast=''high'']"}' AS JSON))
ON DUPLICATE KEY UPDATE
  token_value = VALUES(token_value),
  source = VALUES(source),
  context = VALUES(context),
  selector = VALUES(selector),
  token_category = VALUES(token_category),
  display_order = VALUES(display_order),
  metadata = VALUES(metadata),
  updated_at = CURRENT_TIMESTAMP;

DELETE FROM ux_research_insights;
INSERT INTO ux_research_insights (slug, title, status, recorded_at, owner, summary, tokens_impacted, documents, participants, evidence_url, metadata)
VALUES
  ('design-system-parity-may-2025', 'Design system parity verification (May 2025)', 'completed', '2025-05-20', 'Design Systems', 'Verified generated web and Flutter tokens across light, dark, and high-contrast modes with evidence captured for Annex A55.', CAST('["--color-surface","--shadow-focus-ring","--form-field-border","--form-field-padding-x"]' AS JSON), CAST('["docs/design-system/design_tokens.json","user experience.md"]' AS JSON), CAST('["12 remote learners (diary study)","Design Systems triad"]' AS JSON), 'vault://research/design-system-parity-may-2025', CAST('{"version":"2025-05-26","index":0}' AS JSON)),
  ('accessibility-audit-dark-high-contrast', 'Accessibility audit – dark & high-contrast', 'in_progress', '2025-05-24', 'Accessibility Guild', 'Validating regenerated Flutter themes and React surfaces against WCAG AA targets for dark mode and high-contrast annex flows.', CAST('["--color-text","--color-primary-soft","--skeleton-highlight"]' AS JSON), CAST('["docs/design-system/design_tokens.json","docs/design-system/navigation-annex.md"]' AS JSON), CAST('["6 accessibility specialists","QA automation harness"]' AS JSON), 'zeplin://a11y/dark-mode-audit', CAST('{"version":"2025-05-26","index":1}' AS JSON)),
  ('multi-surface-onboarding-intercepts', 'Multi-surface onboarding intercepts', 'scheduled', '2025-06-05', 'Product Research', 'Diary-guided intercepts following learners from marketing site to native app to confirm spacing and CTA tokens carry over.', CAST('["--grid-gap","--space-6","--form-field-surface"]' AS JSON), CAST('["user experience.md","docs/operations/strategy.md"]' AS JSON), CAST('["Ops research partner panel"]' AS JSON), 'notion://research/activation/2025-06-intercepts', CAST('{"version":"2025-05-26","index":2}' AS JSON)),
  ('stakeholder-comms-tone-testing', 'Stakeholder communications tone testing', 'planned', '2025-06-20', 'Design Ops', 'Co-create investor and board templates ensuring Annex A56 narratives match UX-led tone guidance before the Q3 brief.', CAST('["--color-primary","--gradient-cta","--font-family-sans"]' AS JSON), CAST('["docs/operations/templates/investor-update-outline.md","docs/operations/templates/board-brief-outline.md"]' AS JSON), CAST('["Investor advisory group","Founder"]' AS JSON), 'drive://comms/voice-and-tone/a56', CAST('{"version":"2025-05-26","index":3}' AS JSON))
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  status = VALUES(status),
  recorded_at = VALUES(recorded_at),
  owner = VALUES(owner),
  summary = VALUES(summary),
  tokens_impacted = VALUES(tokens_impacted),
  documents = VALUES(documents),
  participants = VALUES(participants),
  evidence_url = VALUES(evidence_url),
  metadata = VALUES(metadata),
  updated_at = CURRENT_TIMESTAMP;

