name: Generate SLSA Provenance

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  actions: read
  id-token: write
  contents: read

jobs:
  build-provenance:
    name: Build provenance attestation
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subject: true
      upload-assets: true
      provenance-name: edulure-platform-provenance.intoto.jsonl
